"""Compile the reviewed Antofagasta rows into the browser/server fallback seed."""
from pathlib import Path
import csv, hashlib, json, re

ROOT = Path(__file__).resolve().parents[1]
rows = list(csv.DictReader((ROOT/'data/calendar-antofagasta-2026.tsv').open(encoding='utf-8'), delimiter='|'))
events = []
for row in rows:
    title = row['title']
    kind = 'Trámite académico'
    if any(x in title.lower() for x in ['evaluacion', 'evaluación', 'evaluaciones', 'exámenes']): kind = 'Evaluaciones'
    if 'inscripción' in title.lower(): kind = 'Inscripción'
    if any(x in title.lower() for x in ['receso', 'vacaciones', 'feriado']): kind = 'Receso'
    if 'autocuidado' in title.lower(): kind = 'Bienestar'
    if 'clases' in title.lower() or 'cierre académico' in title.lower(): kind = 'Fecha académica'
    if 'Verano' in title: kind = 'Cursos de verano'
    if row['audience'] == 'unidades': kind = 'Gestión académica'
    event = dict(id='evt-acad-'+row['date'].replace('-','')+'-'+hashlib.sha256(title.encode()).hexdigest()[:6], title=title, type=kind, date=row['date'], time='', description=row['description'], campus='Antofagasta', audience=row['audience'], sourcePage=int(row['page']))
    if row['endDate']: event['endDate'] = row['endDate']
    if row['date'] in ['2026-08-08','2026-12-30'] and '13:00' in row['description']: event['time'] = '13:00'
    if row['date'].startswith('2027'): event['provisional'] = True
    events.append(event)
source = dict(version='dgpre-antofagasta-decreto-077-2026-reviewed-20260921', title='Calendario de Actividades Docentes de Pregrado Antofagasta 2026', institution='Dirección General de Pregrado UCN', campus='Antofagasta', updatedAt='2026-07-08', reviewedAt='2026-09-21', coverageStart='2026-07-01', coverageEnd='2027-01-31', decree='Decreto N°77/2026', url='https://www.ucn.cl/content/uploads/2026/08/077-modifica-Calendario-de-Actividades-Docentes-Antofagasta-DGPRE-090-2026-VF-13-Julio-3.pdf', fileUrl='assets/documents/calendario-antofagasta-077-2026.pdf', note='Julio 2026 a enero 2027. La planificación de enero está sujeta a modificaciones.')
target = ROOT/'src/mock-data.js'
text = target.read_text(encoding='utf-8')
start, end = text.index('  const events = ['), text.index('  const agreements = [')
block = '  // Generated by scripts/build-academic-calendar.py; reviewed against PDF pages 3-6.\n  const events = '+json.dumps(events,ensure_ascii=False,indent=2)+';\n\n  const calendarSource = '+json.dumps(source,ensure_ascii=False,indent=2)+';\n\n'
# Keep regeneration idempotent, including the generated comment.
prefix = text[:start]
comment = '  // Generated by scripts/build-academic-calendar.py; reviewed against PDF pages 3-6.\n'
if prefix.endswith(comment): prefix = prefix[:-len(comment)]
text = prefix+block+text[end:]
target.write_text(text,encoding='utf-8')
print(json.dumps({'events':len(events),'campus':source['campus'],'periods':sum('endDate' in e for e in events),'provisional':sum(e.get('provisional',False) for e in events)}))
